<?php

namespace DesignPatterns\Behavioral;

use SplObserver;
use SplSubject;

/**
 * Subject owns some important state and notifies observers when the state changes.
 * PHP has several built-in interfaces \SplSubject, \SplObserver which help us
 * to build implementations of the Observer
 */
class Process implements \SplSubject
{
    /**
     * Some business logic state
     * @var int
     */
    protected $priority = 0;

    /**
     * List of observers
     * Tip: you also can use \SplObjectStorage instead of simple array
     * @var array
     */
    private $observers = [];

    /**
     * Attach an observer
     * @param SplObserver $observer
     */
    public function attach(SplObserver $observer)
    {
        $this->observers[] = $observer;
    }

    /**
     * Detach an observer
     * @param SplObserver $observer
     */
    public function detach(SplObserver $observer)
    {
        foreach ($this->observers as $key => $obs) {
            if ($obs === $observer) {
                unset($this->observers[$key]);
            }
        }
    }

    /**
     * Notify an observer
     */
    public function notify()
    {
        foreach ($this->observers as $observer) {
            $observer->update($this);
        }
    }

    // Business logic

    /**
     * Changes state
     * @param integer $priority
     */
    public function setPriority(int $priority)
    {
        $this->priority = $priority;
        $this->notify();
    }

    /**
     * Return current state
     */
    public function getPriority()
    {
        return $this->priority;
    }
}

/**
 * Concrete observers react to the updates generated by the subject they had been attached to
 */
class LoggingListener implements SplObserver
{
    /**
     * Receive update from subject
     * @param SplSubject $subject
     */
    public function update(SplSubject $subject)
    {
        if (!$subject instanceof Process) {
            return;
        }

        echo 'Notification: process priority was changed to ' . $subject->getPriority();
    }
}

# Client code example
$process = new Process();
$process->attach(new LoggingListener());

$process->setPriority(10);

/* Output:
Notification: process priority was changed to: 10 */